import { exams, questions, students, tenants, users } from '@/data/seed';
import { AuthUser, Exam, Student, Tenant } from '@/types';
import { storage } from './storage';
const wait = (ms = 220) => new Promise(resolve => setTimeout(resolve, ms));
export const authService = {
  async login(email: string, password: string) { await wait(180); const match = users.find(u => u.email === email); const passwords: Record<string,string> = {'admin@quizset.demo':'admin123','owner@sunrise.demo':'owner123','rahul@student.demo':'student123'}; if (!match || passwords[email] !== password) throw new Error('Check your email and password.'); storage.set('auth', match); return match; },
  logout() { storage.remove('auth'); },
  current() { return storage.get<AuthUser|null>('auth', null); },
};
export const tenantService = { list: async () => { await wait(); return tenants; }, create: async (data: Partial<Tenant>) => { await wait(); const item: Tenant = { id: `tenant-${Date.now()}`, name:data.name || 'New Coaching', initials:(data.name || 'NC').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase(), city:data.city || 'India', students:0, plan:data.plan || 'Starter', primaryColor:data.primaryColor || '#4f46e5', joinCode:`${(data.name || 'COACHING').replace(/\s/g,'').slice(0,7).toUpperCase()}2026`, owner:data.owner || 'Owner', supportEmail:data.supportEmail || 'support@example.in' }; const all=storage.get<Tenant[]>('tenants',tenants); storage.set('tenants',[...all,item]); return item; } };
export const examService = { list: async (tenantId?: string) => { await wait(); return storage.get<Exam[]>('exams', exams).filter(e => !tenantId || e.tenantId === tenantId); }, get: async (id:string) => { await wait(); return storage.get<Exam[]>('exams', exams).find(e=>e.id===id) || exams[0]; }, create: async (data: Partial<Exam>) => { await wait(); const item = { ...exams[1], ...data, id:`exam-${Date.now()}`, status:'Draft' as const, students:0 }; const all=storage.get<Exam[]>('exams',exams); storage.set('exams',[...all,item]); return item; }, update: async (id:string, data:Partial<Exam>) => { const all=storage.get<Exam[]>('exams',exams).map(e=>e.id===id?{...e,...data}:e); storage.set('exams',all); return all.find(e=>e.id===id)!; } };
export const studentService = { list: async (tenantId='sunrise') => { await wait(); return storage.get<Student[]>('students',students).filter(s=>s.tenantId===tenantId); }, update: async (id:string, data:Partial<Student>) => { const all=storage.get<Student[]>('students',students).map(s=>s.id===id?{...s,...data}:s); storage.set('students',all); return all.find(s=>s.id===id)!; } };
export const questionService = { list: async () => { await wait(); return storage.get('questions',questions); } };
export const paymentService = { purchase: async (examId:string, amount:number) => { await wait(1200); const purchases=storage.get<string[]>('purchases',[]); storage.set('purchases',[...purchases,examId]); return { id:`QS-TXN-${Math.random().toString(36).slice(2,7).toUpperCase()}`, examId, amount }; }, purchased: (examId:string) => storage.get<string[]>('purchases',[]).includes(examId) };
export const notificationService = { list: async () => { await wait(); return storage.get('notifications',[{id:'n1',title:'Question bank ready',body:'Your Railway Group D bank is ready to configure.',time:'12 min ago',read:false},{id:'n2',title:'Live test reminder',body:'SSC CGL Grand Test begins tomorrow at 10:00 AM.',time:'2 hr ago',read:false},{id:'n3',title:'New purchase',body:'24 students purchased SSC CGL Premium Mock Test.',time:'Yesterday',read:true}]); }, markRead: (id:string) => { const items=storage.get<any[]>('notifications',[]).map(n=>n.id===id?{...n,read:true}:n); storage.set('notifications',items); } };
export const aiService = { async reply(message:string) { await wait(850); const text=message.toLowerCase(); if(text.includes('percentage')) return 'Percentage is your focus area today. Start with 10 medium questions, then review each incorrect step.'; if(text.includes('plan')) return 'Your study plan has 3 tasks left today. I recommend a 25-minute Quantitative Aptitude sprint before the evening mock.'; return 'I can help you with weak topics, exam strategy, and your study plan. Ask me about Percentage or your next practice session.'; } };