import { type ButtonHTMLAttributes, type ReactNode } from 'react';
import { X } from 'lucide-react';
export function Button({children,className='',variant='primary',...props}:{children:ReactNode;className?:string;variant?:'primary'|'secondary'|'ghost'|'danger' } & ButtonHTMLAttributes<HTMLButtonElement>) { return <button {...props} className={`btn btn-${variant} ${className}`}>{children}</button> }
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'success'|'warning'|'danger'|'info'}) { return <span className={`badge badge-${tone}`}>{children}</span> }
export function Card({children,className=''}:{children:ReactNode;className?:string}) { return <section className={`card ${className}`}>{children}</section> }
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}) { return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal"><div className="modal-head"><h3>{title}</h3><button data-testid="button-close-modal" onClick={onClose} className="icon-btn" aria-label="Close"><X size={18}/></button></div>{children}</div></div> }
export function PageHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}) { return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div> }
export function Stat({label,value,delta,icon}:{label:string;value:string;delta?:string;icon?:ReactNode}) { return <Card className="stat-card"><div className="stat-top"><span className="stat-icon">{icon}</span><span className="stat-label">{label}</span></div><strong>{value}</strong>{delta&&<small className="stat-delta">{delta}</small>}</Card> }
export function EmptyState({title,description,action}:{title:string;description:string;action?:ReactNode}) { return <div className="empty"><div className="empty-mark">QS</div><h3>{title}</h3><p>{description}</p>{action}</div> }
export function Field({label,children,required}:{label:string;children:ReactNode;required?:boolean}) { return <label className="field"><span>{label}{required&&<i> *</i>}</span>{children}</label> }